### ISSUE TITLE
Cannot run the example in README

### ISSUE THREAD

**Issue by XZ-X** [BinTuner/Dev#4] opened 2021-07-10 12:13 UTC
Hi,
I'm trying to run the bzip2 example mentioned in `README.md`. Under the  `Dev/BinTuner/examples/gccflags` directory, I tried to run the command `python2 bzip2_gcc.py 10`. Then Python complains the file `Dev/BinTuner/examples/gccflags/../../opentuner/utils/adddeps.py` cannot be found.
I manually looked up the source directory and also could not find the file `adddeps.py`.

The full error information is attached:
```
Traceback (most recent call last):
  File "bzip2_gcc.py", line 3, in <module>
    import adddeps
  File "/...../Dev/BinTuner/examples/gccflags/adddeps.py", line 6, in <module>
    execfile(target, dict(__file__=target))
IOError: [Errno 2] No such file or directory: '/....../Dev/BinTuner/examples/gccflags/../../open
tuner/utils/adddeps.py'
```

Thanks,
XZ-X

**Comment by Patrick-ICT** [comment] 2021-07-13 08:49
Me too. All the examples are requiring that file. I have checked all the commits and still couldn't find that file. Is there any other way to run it?

**Comment by XZ-X** [comment] 2021-07-13 08:54
> Me too. All the examples are requiring that file. I have checked all the commits and still couldn't find that file. Is there any other way to run it?

As a workaround, I symbolically linked `Dev/BinTuner/main` to `Dev/BinTuner/examples/gccflags/opentuner`, and commented out the code in file `Dev/BinTuner/examples/gccflags/adddeps.py`. This symbolic link seems to solve this issue. Nevertheless, I encountered further problems. I'm not sure whether these problems are caused by this workaround.

**Comment by Patrick-ICT** [comment] 2021-07-13 08:57
Thx, I'll have a try.

**Comment by Gxiandy** [comment] 2021-07-14 09:42
I have the same problem, 

> > Me too. All the examples are requiring that file. I have checked all the commits and still couldn't find that file. Is there any other way to run it?
> 
> As a workaround, I symbolically linked `Dev/BinTuner/main` to `Dev/BinTuner/examples/gccflags/opentuner`, and commented out the code in file `Dev/BinTuner/examples/gccflags/adddeps.py`. This symbolic link seems to solve this issue. Nevertheless, I encountered further problems. I'm not sure whether these problems are caused by this workaround.

I got the same problem a few days ago，and tried your solution.  After that, i got a runtime error like this:
TypeError: 'CMD' is an invalid keyword argument for Result
have you meet the same problem before? is there any way to fix this?

**Comment by XZ-X** [comment] 2021-07-14 09:44
> I have the same problem,
> 
> > > Me too. All the examples are requiring that file. I have checked all the commits and still couldn't find that file. Is there any other way to run it?
> > 
> > 
> > As a workaround, I symbolically linked `Dev/BinTuner/main` to `Dev/BinTuner/examples/gccflags/opentuner`, and commented out the code in file `Dev/BinTuner/examples/gccflags/adddeps.py`. This symbolic link seems to solve this issue. Nevertheless, I encountered further problems. I'm not sure whether these problems are caused by this workaround.
> 
> I got the same problem a few days ago，and tried your solution. After that, i got a runtime error like this:
> TypeError: 'CMD' is an invalid keyword argument for Result
> have you meet the same problem before? is there any way to fix this?

I encountered the same problem and am still working on it...

**Comment by xiaoleiren** [comment] 2021-07-15 09:02
@Patrick-ICT @XZ-X @Gxiandy  Hi guys, thanks for your interest in BinTuner, I am following up on this issue, please give me some time, I will try to run this example again on Ubuntu, will fix/update it if there are any new gains :-)

**Comment by BinTuner** [comment] 2021-07-15 09:03
@Patrick-ICT @XZ-X @Gxiandy Hi guys, thanks for your interest in BinTuner, I am following up on this issue, please give me some time, I will try to run this example again on Ubuntu, will fix/update it if there are any new gains :-)

**Comment by BinTuner** [comment] 2021-07-15 09:05
@Patrick-ICT @XZ-X @Gxiandy Hi guys, thanks for your interest in BinTuner, I am following up on this issue, please give me some time, I will try to run this example again on Ubuntu, I will fix/update it if there are any new discoveries :-)

**Comment by BinTuner** [comment] 2021-07-19 05:48
@Patrick-ICT @XZ-X @Gxiandy 
Hi guys,  I have updated some files, please download the entire zip again and try to run it like this: ~/BinTuner/examples/gccflags$ python main.py 2
Feel free to let me know if you have any other questions, thanks!
Have a nice day!

**Comment by XZ-X** [comment] 2021-07-19 06:07
Thank you for the fix.
I ran `python2 main.py 2` under the directory `/.../Dev/BinTuner/examples/gccflangs`, and encountered the following exception:
```
Traceback (most recent call last):
  File "main.py", line 345, in <module>
    GccFlagsTuner.main(args)
  File "/.../Dev/BinTuner/opentuner/measurement/interface.py", line 304, in main
    return TuningRunMain(cls(args, *pargs, **kwargs), args).main()
  File "/.../Dev/BinTuner/opentuner/tuningrunmain.py", line 199, in main
    List = self.search_driver.main() #Michael tuning finish
  File "/.../Dev/BinTuner/opentuner/search/driver.py", line 266, in main
    if self.run_generation_techniques() > 0:
  File "/.../Dev/BinTuner/opentuner/search/driver.py", line 164, in run_generation_techniques
    dr = self.root_technique.desired_result()
  File "/.../Dev/BinTuner/opentuner/search/metatechniques.py", line 39, in desired_result
    dr = technique.desired_result()
  File "/.../Dev/BinTuner/opentuner/search/technique.py", line 87, in desired_result
    cfg = self.desired_configuration()
  File "/.../Dev/BinTuner/opentuner/search/globalGA.py", line 74, in desired_configuration
    z3first,z3second,z3third,z3fouth,z3fifth = Z3Prover.z3function(options = optionsDic)
  File "/.../Dev/BinTuner/opentuner/search/Z3Prover.py", line 6, in z3function
    p, q, w, first, second, third, four, five = Bools('p q w first second third four five')
  File "/.../Dev/BinTuner/opentuner/search/z3/z3.py", line 1497, in Bools
    ctx = _get_ctx(ctx)
  File "/.../Dev/BinTuner/opentuner/search/z3/z3.py", line 220, in _get_ctx
    return main_ctx()
  File "/.../Dev/BinTuner/opentuner/search/z3/z3.py", line 215, in main_ctx
    _main_ctx = Context()
  File "/.../Dev/BinTuner/opentuner/search/z3/z3.py", line 160, in __init__
    conf = Z3_mk_config()
  File "/.../Dev/BinTuner/opentuner/search/z3/z3core.py", line 1272, in Z3_mk_config
    r = lib().Z3_mk_config()
  File "/.../Dev/BinTuner/opentuner/search/z3/z3core.py", line 22, in lib
    raise Z3Exception("init(Z3_LIBRARY_PATH) must be invoked before using Z3-python")
opentuner.search.z3.z3types.Z3Exception: init(Z3_LIBRARY_PATH) must be invoked before using Z3-python
Exception AttributeError: "Context instance has no attribute 'lib'" in <bound method Context.__del__ of <opentuner.search.z3.z3.Context instance at 0x7fef2dabf248>> ignored
```

Thank you again for your help!

**Comment by BinTuner** [comment] 2021-07-19 06:16
an error occurred when invoking z3 ...@XZ-X
Let me think about how to reproduce this error. This should be a common error of z3.

**Comment by BinTuner** [comment] 2021-12-20 13:30
Hi guys,

Some of you have encountered Z3 errors when trying to run BinTuner. I am using z3-solver 4.8.14.0 (pip install z3-solver), just try to use this version and let me know which version of z3-solver you are reporting so that I can go find out what the problem is.

**Comment by BinTuner** [comment] 2021-12-26 14:22
Hi @XZ-X 

I am using z3-solver 4.8.14.0 (pip install z3-solver), I try to install BinTuner again, and this version of z3 works well.
Can you let me know which version of z3-solver you are reporting so that I can go find out what the problem is?

**Comment by BinTuner** [comment] 2021-12-27 19:34
Hi guys,

@Patrick-ICT @XZ-X @Gxiandy 

I've tried a few different solutions to your Z3 issue over the past few days. I have updated some source files and tried to install BinTuner a few times, it should work well now.
Feel free to re-download all the source programs and run BinTuner again.
Let me know if you encounter a new issue. 
Happy New Year!

**Comment by BinTuner** [comment] 2022-07-25 03:55
Hi guys  : ）

Thank you very much for your interest and feedback!

This question has been answered, let me close it for now and if you have other questions, feel free to open a new one.

All the best,

**Closed as completed by BinTuner** 2022-07-25 03:55 UTC
